using TypedRest.CodeGeneration.Endpoints;
using TypedRest.CodeGeneration.Endpoints.Raw;
using TypedRest.CodeGeneration.Endpoints.Reactive;
using TypedRest.CodeGeneration.Endpoints.Rpc;
using TypedRest.CodeGeneration.Generation;
using TypedRest.CodeGeneration.TypeScript.Model;
using CollectionEndpointModel = TypedRest.CodeGeneration.Endpoints.Generic.CollectionEndpoint;
using ElementEndpointModel = TypedRest.CodeGeneration.Endpoints.Generic.ElementEndpoint;
using IndexerEndpointModel = TypedRest.CodeGeneration.Endpoints.Generic.IndexerEndpoint;

namespace TypedRest.CodeGeneration.TypeScript.Endpoints;

public class EndpointGeneratorFacts
{
    private readonly CollectingGenerationLog _log = new();

    private EndpointGenerator Generator()
        => new(new NamingStrategy("MyService", "", "dtos"), BuilderRegistry.Default) {Log = _log};

    private string Generate(EntryEndpoint entry)
    {
        var files = OpenApiDocumentExtensions.ToFiles(Generator().Generate(entry), generateIndex: false);
        return string.Join("\n", files.Select(x => $"=== {x.Path}\n{x.GetContent()}"));
    }

    private TsClass ClassFor(EntryEndpoint entry, string name)
        => Generator().Generate(entry).OfType<TsClass>().Single(x => x.Identifier.Name == name);

    [Fact]
    public void GeneratesCorrectSource()
        => Generate(Sample.EntryEndpoint).Should().Be(
            """
            === MyServiceClient.ts
            // Generated by TypedRest.CodeGeneration. Do not edit.
            import {EntryEndpoint} from "typedrest/endpoints";
            import {GenericCollectionEndpoint} from "typedrest/endpoints/generic";
            import {ContactElementEndpoint} from "./ContactElementEndpoint";
            import {Contact} from "./dtos/Contact";

            export class MyServiceClient extends EntryEndpoint {
              /** Collection of contacts. */
              get contacts(): GenericCollectionEndpoint<Contact, ContactElementEndpoint> {
                return new GenericCollectionEndpoint<Contact, ContactElementEndpoint>(this, "./contacts", ContactElementEndpoint);
              }
            }

            === ContactElementEndpoint.ts
            // Generated by TypedRest.CodeGeneration. Do not edit.
            import {ElementEndpoint} from "typedrest/endpoints/generic";
            import {BlobEndpoint} from "typedrest/endpoints/raw";
            import {ActionEndpoint} from "typedrest/endpoints/rpc";
            import {Contact} from "./dtos/Contact";
            import {Note} from "./dtos/Note";

            /** A specific contact. */
            export class ContactElementEndpoint extends ElementEndpoint<Contact> {
              /** The note for a specific contact. */
              get note(): ElementEndpoint<Note> {
                return new ElementEndpoint<Note>(this, "./note");
              }

              /** Pokes a contact. */
              get poke(): ActionEndpoint {
                return new ActionEndpoint(this, "./poke");
              }

              /** A picture of a specific contact. */
              get picture(): BlobEndpoint {
                return new BlobEndpoint(this, "./picture");
              }
            }

            """.ReplaceLineEndings("\n"));

    /// <summary>
    /// An element endpoint is handed a URI per element by the collection or indexer that owns it. Baking one in
    /// still compiles - TypeScript accepts a constructor with fewer parameters - but every element would then
    /// silently resolve to the same URI at runtime, which no type check can catch.
    /// </summary>
    [Fact]
    public void ElementClassNeverHardCodesUri()
    {
        var element = ClassFor(Sample.EntryEndpoint, "ContactElementEndpoint");

        // Nothing to hard-code a URI into: the inherited (referrer, relativeUri) constructor is exactly right
        element.Constructor.Should().BeNull();
    }

    [Fact]
    public void ElementClassForwardsUriWhenItNeedsExtraArguments()
    {
        var entry = new EntryEndpoint
        {
            Children =
            {
                ["projects"] = new IndexerEndpointModel
                {
                    Uri = "./projects",
                    // The element is itself a collection, so it needs its own element class as a third argument
                    Element = new CollectionEndpointModel
                    {
                        Schema = Sample.NoteSchema,
                        // Children force a class to be generated for the element itself
                        Children = {["ping"] = new ActionEndpoint {Uri = "./ping"}},
                        Element = new ElementEndpointModel {Schema = Sample.NoteSchema, Children = {["poke"] = new ActionEndpoint {Uri = "./poke"}}}
                    }
                }
            }
        };

        var element = ClassFor(entry, "ProjectElementEndpoint");

        element.Constructor!.Parameters.Select(x => x.Name).Should().Equal("referrer", "relativeUri");
        element.Constructor.SuperArguments.Select(x => x.ToCode()).Should().Equal("referrer", "relativeUri", "ProjectElementElementEndpoint");
    }

    [Fact]
    public void UsesCollectionEndpointWhenElementNeedsNoClass()
    {
        var entry = new EntryEndpoint
        {
            Children =
            {
                ["contacts"] = new CollectionEndpointModel
                {
                    Uri = "./contacts",
                    Schema = Sample.ContactSchema,
                    Element = new ElementEndpointModel {Schema = Sample.ContactSchema}
                }
            }
        };

        var getter = ClassFor(entry, "MyServiceClient").Getters.Single();

        getter.Type.ToTypeExpression().Should().Be("CollectionEndpoint<Contact>");
        getter.Body.ToCode().Should().Be("""new CollectionEndpoint<Contact>(this, "./contacts")""");
    }

    [Fact]
    public void PassesElementClassAsConstructorArgumentToIndexer()
    {
        var entry = new EntryEndpoint
        {
            Children =
            {
                ["projects"] = new IndexerEndpointModel
                {
                    Uri = "./projects",
                    Element = new ElementEndpointModel {Schema = Sample.NoteSchema}
                }
            }
        };

        var getter = ClassFor(entry, "MyServiceClient").Getters.Single();

        // The element needs no class of its own, so the built-in one is passed as the factory
        getter.Type.ToTypeExpression().Should().Be("IndexerEndpoint<ElementEndpoint<Note>>");
        getter.Body.ToCode().Should().Be("""new IndexerEndpoint<ElementEndpoint<Note>>(this, "./projects", ElementEndpoint)""");
    }

    [Fact]
    public void PassesFormFieldToUploadEndpoint()
    {
        var entry = new EntryEndpoint
        {
            Children = {["upload"] = new UploadEndpoint {Uri = "./upload", FormField = "file"}}
        };

        ClassFor(entry, "MyServiceClient").Getters.Single().Body.ToCode()
                                          .Should().Be("""new UploadEndpoint(this, "./upload", "file")""");
    }

    [Fact]
    public void PrefixesCollidingKeysWithParent()
    {
        var entry = new EntryEndpoint
        {
            Children =
            {
                ["users"] = new Endpoint
                {
                    Uri = "./users",
                    Children = {["settings"] = new Endpoint {Uri = "./settings", Children = {["theme"] = new ActionEndpoint {Uri = "./theme"}}}}
                },
                ["accounts"] = new Endpoint
                {
                    Uri = "./accounts",
                    Children = {["settings"] = new Endpoint {Uri = "./settings", Children = {["limit"] = new ActionEndpoint {Uri = "./limit"}}}}
                }
            }
        };

        var names = Generator().Generate(entry).OfType<TsClass>().Select(x => x.Identifier.Name).ToList();

        names.Should().Contain(["UsersSettingsEndpoint", "AccountsSettingsEndpoint"]);
        names.Should().NotContain("SettingsEndpoint");
    }

    [Fact]
    public void NumbersTypeNamesThatCollideDespitePrefixes()
    {
        var entry = new EntryEndpoint
        {
            Children =
            {
                ["contracts"] = new Endpoint
                {
                    Uri = "./contracts",
                    Children = {["commits"] = new Endpoint {Uri = "./commits", Children = {["edit"] = new ActionEndpoint {Uri = "./edit"}}}}
                },
                ["customers"] = new Endpoint
                {
                    Uri = "./customers",
                    Children =
                    {
                        ["contracts"] = new Endpoint
                        {
                            Uri = "./contracts",
                            Children = {["commits"] = new Endpoint {Uri = "./commits", Children = {["retire"] = new ActionEndpoint {Uri = "./retire"}}}}
                        }
                    }
                }
            }
        };

        var classes = Generator().Generate(entry).OfType<TsClass>().ToList();

        classes.Select(x => x.Identifier.Name).Should().Contain(["ContractsCommitsEndpoint", "CustomersContractsCommitsEndpoint"]);
        classes.Select(x => x.Identifier.Name).Should().OnlyHaveUniqueItems();
        classes.Select(x => x.Identifier.Module!.Specifier).Should().OnlyHaveUniqueItems();
    }

    [Fact]
    public void OmitsEntryConstructor()
    {
        var entry = ClassFor(Sample.EntryEndpoint, "MyServiceClient");

        // The inherited constructor already takes the base URI plus serializer, error handler and HTTP client
        entry.Constructor.Should().BeNull();
        entry.BaseType!.Name.Should().Be("EntryEndpoint");
    }

    [Fact]
    public void BakesRelativeUriIntoGeneratedClasses()
    {
        var entry = new EntryEndpoint
        {
            Children =
            {
                ["users"] = new Endpoint {Uri = "./users", Children = {["ping"] = new ActionEndpoint {Uri = "./ping"}}}
            }
        };

        var users = ClassFor(entry, "UsersEndpoint");

        users.Constructor!.Parameters.Select(x => x.Name).Should().Equal("referrer");
        users.Constructor.SuperArguments.Select(x => x.ToCode()).Should().Equal("referrer", "\"./users\"");
    }

    [Theory]
    [InlineData("TRCG101")]
    public void WarnsAboutPolling(string code)
    {
        var entry = new EntryEndpoint
        {
            Children = {["status"] = new PollingEndpoint {Uri = "./status", Schema = Sample.NoteSchema}}
        };

        ClassFor(entry, "MyServiceClient").Getters.Single().Type.ToTypeExpression().Should().Be("ElementEndpoint<Note>");
        _log.Messages.Should().ContainSingle().Which.Code.Should().Be(code);
        _log.Messages.Single().Text.Should().Contain("status").And.Contain("ElementEndpoint<Note>");
    }

    [Fact]
    public void WarnsAboutStreamingAndSse()
    {
        var entry = new EntryEndpoint
        {
            Children =
            {
                ["events"] = new StreamingEndpoint {Uri = "./events", Schema = Sample.NoteSchema, Separator = "\n"},
                ["live"] = new SseStreamingEndpoint {Uri = "./live", Schema = Sample.NoteSchema, EventType = "update"}
            }
        };

        ClassFor(entry, "MyServiceClient").Getters.Select(x => x.Type.ToTypeExpression()).Should().Equal("Endpoint", "Endpoint");
        _log.Messages.Select(x => x.Code).Should().Equal("TRCG102", "TRCG103");
        _log.Messages.Select(x => x.EndpointKey).Should().Equal("events", "live");
    }

    [Fact]
    public void WarnsAboutStreamingCollection()
    {
        var entry = new EntryEndpoint
        {
            Children =
            {
                ["contacts"] = new StreamingCollectionEndpoint {Uri = "./contacts", Schema = Sample.ContactSchema}
            }
        };

        ClassFor(entry, "MyServiceClient").Getters.Single().Type.ToTypeExpression().Should().Be("CollectionEndpoint<Contact>");
        _log.Messages.Should().ContainSingle().Which.Code.Should().Be("TRCG104");
    }

    [Fact]
    public void WarnsAndFallsBackWhenElementSchemaDiffers()
    {
        var entry = new EntryEndpoint
        {
            Children =
            {
                ["contacts"] = new CollectionEndpointModel
                {
                    Uri = "./contacts",
                    Schema = Sample.ContactSchema,
                    // TElementEndpoint is constrained to ElementEndpoint<TEntity>, so this cannot be expressed
                    Element = new ElementEndpointModel {Schema = Sample.NoteSchema}
                }
            }
        };

        ClassFor(entry, "MyServiceClient").Getters.Single().Type.ToTypeExpression().Should().Be("CollectionEndpoint<Contact>");
        _log.Messages.Should().ContainSingle().Which.Code.Should().Be("TRCG105");
    }
}
