using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using NanoByte.CodeGeneration;

namespace TypedRest.CodeGeneration.CSharp;

/// <summary>
/// Generates TypedRest clients from OpenAPI/Swagger documents referenced via <c>TypedRestOpenApi</c> items.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class TypedRestSourceGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Already mapped to a concrete version (e.g. CSharp14), never Latest or Default
        var languageVersion = context.ParseOptionsProvider.Select(static (options, _)
            => options is CSharpParseOptions csharp ? csharp.LanguageVersion : LanguageVersion.Latest);

        var globalConfig = context.AnalyzerConfigOptionsProvider.Select(static (provider, _)
            => GlobalConfig.From(provider.GlobalOptions));

        var specs = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, cancellationToken) => SpecInput.From(pair.Left, pair.Right.GetOptions(pair.Left), cancellationToken))
            .Where(static spec => spec is not null)
            .Select(static (spec, _) => spec!);

        context.RegisterSourceOutput(
            specs.Combine(globalConfig).Combine(languageVersion),
            static (context, data) => Execute(context, data.Left.Left, data.Left.Right, data.Right));
    }

    private static void Execute(SourceProductionContext context, SpecInput spec, GlobalConfig globalConfig, LanguageVersion languageVersion)
    {
        var location = Location.Create(spec.Path, new TextSpan(0, 0), new LinePositionSpan());
        string fileName = PathHelper.FileName(spec.Path);

        if (spec.Content is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(Diagnostics.UnreadableSpec, location, fileName));
            return;
        }

        if ((spec.ServiceName ?? globalConfig.ServiceName) is not {} serviceName)
        {
            context.ReportDiagnostic(Diagnostic.Create(Diagnostics.MissingServiceName, location, fileName));
            return;
        }

        OpenApiDocument doc;
        OpenApiDiagnostic diagnostic;
        try
        {
            doc = new OpenApiStringReader(new OpenApiReaderSettings().AddTypedRest()).Read(spec.Content, out diagnostic);
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(Diagnostics.GenerationFailed, location, fileName, ex.GetType().Name, ex.Message));
            return;
        }

        foreach (var error in diagnostic.Errors)
            context.ReportDiagnostic(Diagnostic.Create(Diagnostics.SpecError, location, fileName, error.Message));
        foreach (var warning in diagnostic.Warnings)
            context.ReportDiagnostic(Diagnostic.Create(Diagnostics.SpecWarning, location, fileName, warning.Message));

        if ((spec.LangVersion ?? globalConfig.LangVersion) is {} langVersion)
        {
            if (LanguageVersionFacts.TryParse(langVersion, out var parsed)) languageVersion = parsed;
            else context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidLangVersion, location, langVersion));
        }

        var options = new GenerationOptions(serviceName)
        {
            Namespace = spec.Namespace ?? globalConfig.Namespace ?? globalConfig.RootNamespace,
            DtoNamespace = spec.DtoNamespace ?? globalConfig.DtoNamespace,
            GenerateInterfaces = spec.GenerateInterfaces ?? globalConfig.GenerateInterfaces ?? true,
            GenerateDtos = spec.GenerateDtos ?? globalConfig.GenerateDtos ?? true,
            LanguageVersion = languageVersion
        };

        string prefix = PathHelper.Sanitize(PathHelper.FileStem(spec.Path));
        var hintNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        try
        {
            foreach (var type in doc.GenerateTypedRest(options))
            {
                context.CancellationToken.ThrowIfCancellationRequested();
                context.AddSource(HintName(hintNames, prefix, type.Identifier), type.ToSyntax().GetText(Encoding.UTF8));
            }
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(Diagnostics.GenerationFailed, location, fileName, ex.GetType().Name, ex.Message));
        }
    }

    /// <summary>
    /// Builds a hint name that is unique across all spec files in a project. Prefixing with the file name of the
    /// spec is what keeps two specs apart, since each of them is generated by a separate invocation.
    /// </summary>
    private static string HintName(HashSet<string> used, string prefix, CSharpIdentifier identifier)
    {
        string baseName = $"{prefix}.{PathHelper.Sanitize(identifier.Namespace ?? "")}.{PathHelper.Sanitize(identifier.Name)}";

        string name = baseName;
        for (int i = 2; !used.Add(name); i++)
            name = $"{baseName}_{i}";
        return name + ".g.cs";
    }
}
