using TypedRest.CodeGeneration.Generation;

namespace TypedRest.CodeGeneration.TypeScript;

public class TypeScriptClientGeneratorFacts
{
    private readonly IClientGenerator _generator = new TypeScriptClientGenerator();

    [Fact]
    public void IsRegisteredUnderTypescript()
        => _generator.Language.Should().Be("typescript");

    [Fact]
    public void CreatesTypeScriptOptions()
        => _generator.CreateOptions("MyService").Should().BeOfType<TypeScriptGenerationOptions>();

    [Fact]
    public void GeneratesOneFilePerTypePlusBarrel()
    {
        var options = new TypeScriptGenerationOptions("MyService") {GenerateDtos = true};

        var files = _generator.Generate(Sample.Doc, options).ToList();

        files.Select(x => x.Path).Should().Equal(
            "MyServiceClient.ts",
            "ContactElementEndpoint.ts",
            "dtos/Contact.ts",
            "dtos/Note.ts",
            "index.ts");

        files.Last().GetContent().Should().Be(
            """
            // Generated by TypedRest.CodeGeneration. Do not edit.

            export * from "./MyServiceClient";
            export * from "./ContactElementEndpoint";
            export * from "./dtos/Contact";
            export * from "./dtos/Note";

            """.ReplaceLineEndings("\n"));
    }

    [Fact]
    public void OmitsDtosUnlessRequested()
        => _generator.Generate(Sample.Doc, new TypeScriptGenerationOptions("MyService"))
                     .Select(x => x.Path).Should().NotContain(x => x.StartsWith("dtos/"));

    [Fact]
    public void OmitsBarrelWhenDisabled()
        => _generator.Generate(Sample.Doc, new TypeScriptGenerationOptions("MyService") {GenerateIndex = false})
                     .Select(x => x.Path).Should().NotContain("index.ts");

    [Fact]
    public void HonorsNamespaceDirectories()
    {
        var options = new TypeScriptGenerationOptions("MyService")
        {
            Namespace = "endpoints",
            DtoNamespace = "models",
            GenerateDtos = true
        };

        _generator.Generate(Sample.Doc, options).Select(x => x.Path).Should().Equal(
            "endpoints/MyServiceClient.ts",
            "endpoints/ContactElementEndpoint.ts",
            "models/Contact.ts",
            "models/Note.ts",
            "index.ts");
    }

    [Fact]
    public void ImportsFromConfiguredPackage()
        => _generator.Generate(Sample.Doc, new TypeScriptGenerationOptions("MyService") {TypedRestPackage = "@acme/typedrest"})
                     .First().GetContent().Should().Contain("""from "@acme/typedrest/endpoints";""");

    [Fact]
    public void WarnsThatInterfacesAreNotSupported()
    {
        var log = new CollectingGenerationLog();

        _generator.Generate(Sample.Doc, new TypeScriptGenerationOptions("MyService") {GenerateInterfaces = true}, log).ToList();

        log.Messages.Should().ContainSingle().Which.Code.Should().Be("TRCG110");
    }

    [Fact]
    public void AcceptsLanguageNeutralOptions()
    {
        var options = new ClientGenerationOptions("MyService") {GenerateDtos = true};

        _generator.Generate(Sample.Doc, options).Select(x => x.Path).Should().Contain("dtos/Contact.ts");
    }

    [Fact]
    public void WritesFilesToDisk()
    {
        string directory = Path.Combine(Path.GetTempPath(), "typedrest-ts-" + Guid.NewGuid().ToString("N"));
        try
        {
            foreach (var file in _generator.Generate(Sample.Doc, new TypeScriptGenerationOptions("MyService") {GenerateDtos = true}))
                file.WriteToDirectory(directory);

            File.Exists(Path.Combine(directory, "MyServiceClient.ts")).Should().BeTrue();
            File.Exists(Path.Combine(directory, "dtos", "Contact.ts")).Should().BeTrue();

            var bytes = File.ReadAllBytes(Path.Combine(directory, "index.ts"));
            bytes.Take(3).Should().NotEqual([0xEF, 0xBB, 0xBF], "the EditorConfig asks for UTF-8 without a BOM");
            File.ReadAllText(Path.Combine(directory, "index.ts")).Should().NotContain("\r\n");
        }
        finally
        {
            if (Directory.Exists(directory)) Directory.Delete(directory, recursive: true);
        }
    }
}
