swagger: '2.0'

info:
  version: v1
  title: My Service
  contact:
    url: 'http://www.example.com'
    email: developer@example.com

x-endpoints:
  contacts:
    type: collection
    description: a collection of contacts
    uri: ./contacts
    schema:
      $ref: "#/definitions/Contact"
    element:
      schema:
        $ref: "#/definitions/Contact"
      children:
        note:
          type: element
          uri: ./note
          schema:
            $ref: "#/definitions/Note"
        poke:
          type: action
          uri: ./poke

paths:
  /:
    get:
      operationId: Home
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  /contacts:
    get:
      summary: Returns all elements.
      operationId: ReadAll
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/Contact'
    post:
      summary: Creates a new element.
      operationId: Create
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: element
          in: body
          description: The element to create (without an ID).
          required: false
          schema:
            $ref: '#/definitions/Contact'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/Contact'
        '400':
          description: Missing or invalid request body
  '/contacts/{id}':
    get:
      summary: Returns a specific element.
      operationId: Read
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          description: The ID of the element to look for.
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Contact'
        '404':
          description: Specified element not found
    put:
      summary: Updates an existing element.
      operationId: Set
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          description: The ID of the element to update (must match the ID in element).
          required: true
          type: string
        - name: element
          in: body
          description: The modified element.
          required: false
          schema:
            $ref: '#/definitions/Contact'
      responses:
        '204':
          description: Success
        '400':
          description: Missing or invalid request body
        '404':
          description: Specified element not found
    delete:
      summary: Deletes an existing element.
      operationId: Delete
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          description: The ID of the element to delete.
          required: true
          type: string
      responses:
        '204':
          description: Success
        '404':
          description: Specified element not found
  '/contacts/{id}/note':
    get:
      summary: Returns the note for a specific contact.
      operationId: ReadNote
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          description: The ID of the contact to get the note for.
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Note'
        '404':
          description: Specified contact not found
    put:
      summary: Sets a note for a specific contact.
      operationId: SetNote
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          description: The ID of the contact to set the note for.
          required: true
          type: string
        - name: note
          in: body
          description: The note to set
          required: false
          schema:
            $ref: '#/definitions/Note'
      responses:
        '200':
          description: OK
        '400':
          description: Missing or invalid request body
        '404':
          description: Specified contact not found
  '/contacts/{id}/poke':
    post:
      summary: Pokes a contact.
      operationId: Poke
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          description: The ID of the contact to poke.
          required: true
          type: string
      responses:
        '204':
          description: Success
        '404':
          description: Specified contact not found

definitions:
  Contact:
    description: A representation of a contact for serialization.
    required:
      - firstName
      - lastName
    type: object
    properties:
      id:
        description: The ID of the contact.
        type: string
      firstName:
        description: The first name of the contact.
        type: string
      lastName:
        description: The last name of the contact.
        type: string
  Note:
    description: A representation of a note for serialization.
    required:
      - content
    type: object
    properties:
      content:
        description: The content of the note
        type: string
