namespace TypedRest.CodeGeneration.Jvm.Model;

/// <summary>
/// A JVM package, e.g. <c>net.typedrest.endpoints.generic</c>.
/// </summary>
public sealed class JvmPackage : IEquatable<JvmPackage>
{
    /// <summary>
    /// Creates a package from a dotted name.
    /// </summary>
    /// <param name="name">The dotted package name. May be empty for the default package.</param>
    /// <param name="generated">Whether this package is generated by this tool rather than coming from a library.</param>
    public JvmPackage(string name, bool generated = false)
    {
        Name = name;
        Generated = generated;
    }

    /// <summary>
    /// A package belonging to the TypedRest runtime library or the JDK.
    /// </summary>
    public static JvmPackage External(string name)
        => new(name);

    /// <summary>
    /// A package holding types generated by this tool.
    /// </summary>
    public static JvmPackage ForGenerated(string name)
        => new(name, generated: true);

    /// <summary>
    /// The dotted package name. Empty for the default package.
    /// </summary>
    public string Name { get; }

    /// <summary>
    /// Indicates whether this package holds types generated by this tool, as opposed to library types.
    /// </summary>
    public bool Generated { get; }

    /// <summary>
    /// The directory this package's files go in, relative to the source root, using <c>/</c> as the separator.
    /// </summary>
    public string Directory
        => Name.Replace('.', '/');

    /// <summary>
    /// The path of a file holding <paramref name="typeName"/> in this package, including the extension.
    /// </summary>
    public string FilePath(string typeName, string extension)
        => Directory.Length == 0 ? typeName + extension : Directory + "/" + typeName + extension;

    /// <summary>
    /// Turns a namespace-style value such as <c>MyCompany.MyService</c> into a valid package name.
    /// </summary>
    public static string Sanitize(string? value)
    {
        if (string.IsNullOrEmpty(value)) return "";

        var segments = value!.Split(['.', '/', '\\'], StringSplitOptions.RemoveEmptyEntries)
                             .Select(SanitizeSegment)
                             .Where(x => x.Length != 0);

        return string.Join(".", segments);
    }

    private static string SanitizeSegment(string segment)
    {
        var chars = segment.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray();
        if (chars.Length == 0) return "";

        string result = new string(chars).ToLowerInvariant();

        // A segment may not start with a digit, and must not collide with a Java keyword
        if (char.IsDigit(result[0]) || JvmSyntax.IsReservedWord(result)) result = "_" + result;

        return result;
    }

    /// <inheritdoc/>
    public bool Equals(JvmPackage? other)
        => other is not null && Name == other.Name;

    /// <inheritdoc/>
    public override bool Equals(object? obj)
        => obj is JvmPackage other && Equals(other);

    /// <inheritdoc/>
    public override int GetHashCode()
        => Name.GetHashCode();

    /// <inheritdoc/>
    public override string ToString()
        => Name;
}
