using TypedRest.CodeGeneration.Generation;

namespace TypedRest.CodeGeneration.TypeScript.Model;

public class TsFileFacts
{
    private static readonly TsModule Generic = TsModule.External("typedrest/endpoints/generic");
    private static readonly TsModule Endpoints = TsModule.External("typedrest/endpoints");
    private static readonly TsModule Dtos = TsModule.Generated("dtos/Contact");

    [Fact]
    public void WritesClassWithGetters()
    {
        var file = new TsFile("ContactEndpoint.ts")
        {
            Types =
            {
                new TsClass(new TsIdentifier(TsModule.Generated("ContactEndpoint"), "ContactEndpoint"))
                {
                    Summary = "A specific contact.",
                    BaseType = new TsIdentifier(Generic, "ElementEndpoint")
                    {
                        TypeArguments = {new TsIdentifier(Dtos, "Contact")}
                    },
                    Getters =
                    {
                        new TsGetter(
                            "note",
                            new TsIdentifier(Generic, "ElementEndpoint") {TypeArguments = {new TsIdentifier(TsModule.Generated("dtos/Note"), "Note")}},
                            new TsNew(new TsIdentifier(Generic, "ElementEndpoint") {TypeArguments = {new TsIdentifier(TsModule.Generated("dtos/Note"), "Note")}})
                            {
                                Arguments = {TsThis.Instance, new TsLiteral("./note")}
                            })
                        {
                            Summary = "The note for a specific contact."
                        }
                    }
                }
            }
        };

        file.GetContent().Should().Be(
            """
            // Generated by TypedRest.CodeGeneration. Do not edit.
            import {ElementEndpoint} from "typedrest/endpoints/generic";
            import {Contact} from "./dtos/Contact";
            import {Note} from "./dtos/Note";

            /** A specific contact. */
            export class ContactEndpoint extends ElementEndpoint<Contact> {
              /** The note for a specific contact. */
              get note(): ElementEndpoint<Note> {
                return new ElementEndpoint<Note>(this, "./note");
              }
            }

            """.ReplaceLineEndings("\n"));
    }

    [Fact]
    public void WritesConstructorBeforeGetters()
    {
        var file = new TsFile("ProjectEndpoint.ts")
        {
            Types =
            {
                new TsClass(new TsIdentifier(TsModule.Generated("ProjectEndpoint"), "ProjectEndpoint"))
                {
                    BaseType = new TsIdentifier(Generic, "GenericCollectionEndpoint"),
                    Constructor = new TsConstructor
                    {
                        Parameters =
                        {
                            new TsParameter("referrer", new TsIdentifier(Endpoints, "Endpoint")),
                            new TsParameter("relativeUri", TsIdentifier.UrlOrString)
                        },
                        SuperArguments =
                        {
                            new TsName("referrer"),
                            new TsName("relativeUri"),
                            new TsTypeRef(new TsIdentifier(TsModule.Generated("TaskEndpoint"), "TaskEndpoint"))
                        }
                    },
                    Getters =
                    {
                        new TsGetter("poke", new TsIdentifier(Endpoints, "Endpoint"), new TsNew(new TsIdentifier(Endpoints, "Endpoint")) {Arguments = {TsThis.Instance, new TsLiteral("./poke")}})
                    }
                }
            }
        };

        file.GetContent().Should().Be(
            """
            // Generated by TypedRest.CodeGeneration. Do not edit.
            import {Endpoint} from "typedrest/endpoints";
            import {GenericCollectionEndpoint} from "typedrest/endpoints/generic";
            import {TaskEndpoint} from "./TaskEndpoint";

            export class ProjectEndpoint extends GenericCollectionEndpoint {
              constructor(referrer: Endpoint, relativeUri: URL | string) {
                super(referrer, relativeUri, TaskEndpoint);
              }

              get poke(): Endpoint {
                return new Endpoint(this, "./poke");
              }
            }

            """.ReplaceLineEndings("\n"));
    }

    [Fact]
    public void WritesInterfaceWithQuotedAndOptionalProperties()
    {
        var file = new TsFile("dtos/Contact.ts")
        {
            Types =
            {
                new TsInterface(new TsIdentifier(Dtos, "Contact"))
                {
                    Summary = "A contact.",
                    BaseTypes = {new TsIdentifier(TsModule.Generated("dtos/Person"), "Person")},
                    Properties =
                    {
                        new TsProperty("id", TsIdentifier.String),
                        new TsProperty("first-name", TsIdentifier.String) {Optional = true, Summary = "The given name."},
                        new TsProperty("tags", TsIdentifier.ArrayOf(TsIdentifier.String.ToNullable())) {Optional = true},
                        new TsProperty("meta", TsIdentifier.RecordOf(TsIdentifier.String, TsIdentifier.Unknown)) {Deprecated = true}
                    }
                }
            }
        };

        file.GetContent().Should().Be(
            """
            // Generated by TypedRest.CodeGeneration. Do not edit.
            import {Person} from "./Person";

            /** A contact. */
            export interface Contact extends Person {
              id: string;
              /** The given name. */
              "first-name"?: string;
              tags?: Array<string | null>;
              /** @deprecated */
              meta: Record<string, unknown>;
            }

            """.ReplaceLineEndings("\n"));
    }

    [Fact]
    public void WritesTypeAlias()
    {
        var file = new TsFile("dtos/Priority.ts")
        {
            Types =
            {
                new TsTypeAlias(new TsIdentifier(TsModule.Generated("dtos/Priority"), "Priority"), "\"low\" | \"high\"")
                {
                    Summary = "How urgent something is."
                }
            }
        };

        file.GetContent().Should().Be(
            """
            // Generated by TypedRest.CodeGeneration. Do not edit.

            /** How urgent something is. */
            export type Priority = "low" | "high";

            """.ReplaceLineEndings("\n"));
    }

    [Fact]
    public void WritesMultiLineDocComments()
    {
        var file = new TsFile("dtos/Thing.ts")
        {
            Types =
            {
                new TsInterface(new TsIdentifier(TsModule.Generated("dtos/Thing"), "Thing"))
                {
                    Summary = "First line.\nSecond line, ending a comment */ here.",
                    Deprecated = true,
                    Properties = {new TsProperty("id", TsIdentifier.String)}
                }
            }
        };

        file.GetContent().Should().Be(
            """
            // Generated by TypedRest.CodeGeneration. Do not edit.

            /**
             * First line.
             * Second line, ending a comment *\/ here.
             * @deprecated
             */
            export interface Thing {
              id: string;
            }

            """.ReplaceLineEndings("\n"));
    }

    [Fact]
    public void OmitsSelfImports()
    {
        var module = TsModule.Generated("dtos/Contact");
        var file = new TsFile("dtos/Contact.ts")
        {
            Types =
            {
                new TsInterface(new TsIdentifier(module, "Contact"))
                {
                    Properties = {new TsProperty("parent", new TsIdentifier(module, "Contact")) {Optional = true}}
                }
            }
        };

        file.GetContent().Should().NotContain("import");
    }

    [Fact]
    public void WritesBarrelFile()
    {
        var file = new TsBarrelFile("index.ts",
        [
            TsModule.Generated("SampleClient"),
            TsModule.Generated("dtos/Contact")
        ]);

        file.Path.Should().Be("index.ts");
        file.GetContent().Should().Be(
            """
            // Generated by TypedRest.CodeGeneration. Do not edit.

            export * from "./SampleClient";
            export * from "./dtos/Contact";

            """.ReplaceLineEndings("\n"));
    }
}
