swagger: '2.0'
info:
  title: My Service
paths:
  /:
    get:
      produces:
        - application/json
      responses:
        '200':
          schema:
            type: string
  /contacts:
    get:
      summary: All contacts.
      produces:
        - application/json
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Contact'
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Contact'
      responses:
        '201':
          schema:
            $ref: '#/definitions/Contact'
  '/contacts/{id}':
    get:
      summary: A specific contact.
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Contact'
    put:
      consumes:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Contact'
      responses:
        '204': { }
    delete:
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '204': { }
  '/contacts/{id}/note':
    get:
      summary: The note for a specific contact.
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Note'
    put:
      consumes:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Note'
      responses:
        '204': { }
  '/contacts/{id}/poke':
    post:
      summary: Pokes a contact.
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '204': { }
definitions:
  Contact:
    description: A contact in an address book.
    required:
      - firstName
      - lastName
    type: object
    properties:
      id:
        description: The ID of the contact.
        type: string
      firstName:
        description: The first name of the contact.
        type: string
      lastName:
        description: The last name of the contact.
        type: string
  Note:
    description: A note about a specific contact.
    required:
      - content
    type: object
    properties:
      content:
        description: The content of the note.
        type: string
x-endpoints:
  contacts:
    type: collection
    description: a collection of contacts
    uri: ./contacts
    element:
      type: element
      children:
        note:
          type: element
          uri: ./note
          schema:
            $ref: '#/definitions/Note'
        poke:
          type: action
          uri: ./poke
    schema:
      $ref: '#/definitions/Contact'
