openapi: 3.0.4
info:
  title: My Service
  version: 1.0.0
paths:
  /:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
  /contacts:
    get:
      responses:
        '200':
          description: Collection of contacts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
  '/contacts/{id}':
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A specific contact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '204':
          description: ''
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: ''
  '/contacts/{id}/note':
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The note for a specific contact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '204':
          description: ''
  '/contacts/{id}/poke':
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Pokes a contact.
  '/contacts/{id}/picture':
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A picture of a specific contact.
          content:
            image/jpeg:
              schema: { }
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          image/jpeg:
            schema: { }
      responses:
        '204':
          description: ''
components:
  schemas:
    Contact:
      required:
        - firstName
        - lastName
      type: object
      properties:
        id:
          type: string
          description: The ID of the contact.
        firstName:
          type: string
          description: The first name of the contact.
        lastName:
          type: string
          description: The last name of the contact.
      description: A contact in an address book.
    Note:
      required:
        - content
      type: object
      properties:
        content:
          type: string
          description: The content of the note.
      description: A note about a specific contact.
x-typedrest:
  contacts:
    kind: collection
    uri: ./contacts
    description: Collection of contacts.
    schema:
      $ref: '#/components/schemas/Contact'
    element:
      kind: element
      description: A specific contact.
      children:
        note:
          kind: element
          uri: ./note
          description: The note for a specific contact.
          schema:
            $ref: '#/components/schemas/Note'
        poke:
          kind: action
          uri: ./poke
          description: Pokes a contact.
        picture:
          kind: blob
          uri: ./picture
          description: A picture of a specific contact.
