using System.Text;
using TypedRest.CodeGeneration.Generation;

namespace TypedRest.CodeGeneration.TypeScript.Model;

/// <summary>
/// A generated TypeScript source file holding one or more type declarations.
/// </summary>
/// <param name="path">The path of the file relative to the output directory, e.g. <c>dtos/Contact.ts</c>.</param>
public sealed class TsFile(string path) : IGeneratedFile
{
    /// <summary>
    /// The header written at the top of every generated file.
    /// </summary>
    public const string Header = "// Generated by TypedRest.CodeGeneration. Do not edit.";

    /// <inheritdoc/>
    public string Path { get; } = path;

    /// <inheritdoc/>
    public Encoding Encoding { get; } = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

    /// <summary>
    /// The types declared in this file.
    /// </summary>
    public List<ITsType> Types { get; } = [];

    /// <inheritdoc/>
    public void WriteTo(TextWriter textWriter)
    {
        var writer = new TsWriter(textWriter);
        writer.WriteLine(Header);

        WriteImports(writer);

        foreach (var type in Types)
        {
            writer.WriteLine();
            type.Write(writer);
        }
    }

    private void WriteImports(TsWriter writer)
    {
        var byModule = Types.SelectMany(x => x.GetImports())
                            // A module never imports from itself
                            .Where(import => !(import.Module.IsGenerated && import.Module.FilePath == Path))
                            .Distinct()
                            .GroupBy(import => import.Module)
                            // Package imports first, then relative ones, each alphabetically
                            .OrderBy(group => group.Key.IsGenerated ? 1 : 0)
                            .ThenBy(group => group.Key.RelativeTo(Path), StringComparer.Ordinal)
                            .ToList();

        foreach (var group in byModule)
        {
            var names = group.Select(import => import.Name).Distinct().OrderBy(name => name, StringComparer.Ordinal);
            writer.WriteLine($"import {{{string.Join(", ", names)}}} from {Ts.Quote(group.Key.RelativeTo(Path))};");
        }
    }
}
