namespace TypedRest.CodeGeneration.TypeScript.Model;

/// <summary>
/// A TypeScript module that a type can be imported from.
/// </summary>
public sealed class TsModule : IEquatable<TsModule>
{
    private TsModule(string specifier, bool isGenerated)
    {
        Specifier = specifier;
        IsGenerated = isGenerated;
    }

    /// <summary>
    /// A module provided by a package, e.g. <c>typedrest/endpoints/generic</c>.
    /// </summary>
    public static TsModule External(string specifier)
        => new(specifier, isGenerated: false);

    /// <summary>
    /// A module generated by this tool, identified by its file path relative to the output directory without the
    /// <c>.ts</c> extension, e.g. <c>dtos/Contact</c>.
    /// </summary>
    public static TsModule Generated(string path)
        => new(path, isGenerated: true);

    /// <summary>
    /// The module specifier. For generated modules this is the file path without the extension.
    /// </summary>
    public string Specifier { get; }

    /// <summary>
    /// Indicates whether this module is generated by this tool rather than provided by a package.
    /// </summary>
    public bool IsGenerated { get; }

    /// <summary>
    /// The path of the file holding this module, relative to the output directory.
    /// </summary>
    /// <exception cref="InvalidOperationException">The module is not generated by this tool.</exception>
    public string FilePath
        => IsGenerated
            ? Specifier + ".ts"
            : throw new InvalidOperationException($"'{Specifier}' is not a generated module.");

    /// <summary>
    /// The last segment of the <see cref="Specifier"/>, which for a generated module is the name of the type it
    /// declares.
    /// </summary>
    public string Name
    {
        get
        {
            int index = Specifier.LastIndexOf('/');
            return index < 0 ? Specifier : Specifier.Substring(index + 1);
        }
    }

    /// <summary>
    /// Returns a copy of this module in the same directory but with a different <see cref="Name"/>.
    /// </summary>
    public TsModule WithName(string name)
    {
        int index = Specifier.LastIndexOf('/');
        return new TsModule(index < 0 ? name : Specifier.Substring(0, index + 1) + name, IsGenerated);
    }

    /// <summary>
    /// Returns the specifier to use when importing this module from the file at <paramref name="fromFilePath"/>.
    /// </summary>
    /// <param name="fromFilePath">The path of the importing file relative to the output directory, e.g. <c>dtos/Contact.ts</c>.</param>
    /// <remarks>
    /// Generated modules get a relative specifier without a file extension. External modules are returned as-is.
    /// This deliberately does not use <see cref="Path"/>, which would emit backslashes on Windows.
    /// </remarks>
    public string RelativeTo(string fromFilePath)
    {
        if (!IsGenerated) return Specifier;

        var fromDirectory = Segments(fromFilePath);
        fromDirectory.RemoveAt(fromDirectory.Count - 1);

        var to = Segments(Specifier);
        string name = to[to.Count - 1];
        to.RemoveAt(to.Count - 1);

        int common = 0;
        while (common < fromDirectory.Count && common < to.Count && fromDirectory[common] == to[common])
            common++;

        var parts = new List<string>();
        for (int i = common; i < fromDirectory.Count; i++) parts.Add("..");
        if (parts.Count == 0) parts.Add(".");
        for (int i = common; i < to.Count; i++) parts.Add(to[i]);
        parts.Add(name);

        return string.Join("/", parts);
    }

    private static List<string> Segments(string path)
        => [..path.Split('/').Where(segment => segment.Length != 0)];

    /// <inheritdoc/>
    public bool Equals(TsModule? other)
        => other != null && Specifier == other.Specifier && IsGenerated == other.IsGenerated;

    /// <inheritdoc/>
    public override bool Equals(object? obj)
        => obj is TsModule other && Equals(other);

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        unchecked
        {
            return (Specifier.GetHashCode() * 397) ^ IsGenerated.GetHashCode();
        }
    }

    /// <inheritdoc/>
    public override string ToString()
        => Specifier;
}
